images:
	chmod a+rx AWS_Logo.jpg
	chmod a+rx C_Logo.png
	chmod a+rx C++_Logo.png
	chmod a+rx Collatz_Logo.png
	chmod a+rx CSS_Logo.webp
	chmod a+rx CyberSecurity_Logo.png
	chmod a+rx Hackathon_Logo.png
	chmod a+rx HTML_Logo.png
	chmod a+rx Java_Logo.png
	chmod a+rx Javascript_Logo.png
	chmod a+rx Kubernetes_Logo.png
	chmod a+rx MachineLearning_Logo.png
	chmod a+rx Python_Logo.png
	chmod a+rx Ruby_logo.png
	chmod a+rx smoliv.png
	chmod a+rx Web_Development_Logo.png